name: Feature Branch PR Manual Action

on:
  workflow_dispatch:
    inputs:
      head_ref:
        description: 'Pull Request Head Branch Name'
        required: true

jobs:
  check_feature_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.head_ref }}

      - name: Check branch prefix and run action
        run: |
          if [[ "${{ github.event.inputs.head_ref }}" == feature-* ]]; then
            echo "This action runs only for feature branch PRs to main"
            # ここに実行したいアクションのコマンドを記述します
            # 例: テストの実行、コード分析、デプロイなど
          else
            echo "This action is only for feature branch PRs. Current branch: ${{ github.event.inputs.head_ref }}"
            exit 1
          fi
