name: Feature Branch PR Manual Action

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    paths:
      - 'test-dir/**'

jobs:
  check_feature_branch:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'feature-')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Your manual action
        run: |
          echo "This action runs only for feature branch PRs to main with changes in test-dir"
          # ここに実行したいアクションのコマンドを記述します
          # 例: テストの実行、コード分析、デプロイなど
